In [32]:
#Load the librarys
import pandas as pd #To work with dataset
import numpy as np #Math library
import seaborn as sns #Graph library that use matplot in background
import matplotlib.pyplot as plt #to plot some parameters in seaborn
from sklearn.neighbors import KNeighborsClassifier

In [2]:
import matplotlib as mpl
mpl.use('TKAgg')
import matplotlib.pyplot as plt
plt.ion();
import matplotlib.cm as cm
import numpy as np
from scipy.spatial import ConvexHull
from sklearn.mixture import GaussianMixture
from scipy import linalg
from sklearn.neighbors import NearestNeighbors

In [3]:
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [4]:
from triedpy import triedctk   as ctk
from triedpy import triedsompy as SOM
import matplotlib as mpl
from matplotlib import cm
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.cluster.hierarchy as sch

In [5]:
import importlib as im
import exo4
im.reload(exo4)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


<module 'exo4' from 'C:\\Users\\HP\\Anaconda3\\Scripts\\Project_DQ\\credit_bank_estimation\\exo4.py'>

In [6]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split

In [7]:
import scipy
from scipy.cluster import hierarchy
import seaborn as sns
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn import preprocessing, model_selection, metrics, feature_selection
from sklearn import (manifold, datasets, decomposition, ensemble,
                     discriminant_analysis, random_projection)
from sklearn.cluster import KMeans

# I . Data Entry 

In [8]:
df_credit = pd.read_csv("german_credit_data_risk.csv",index_col=0)

In [9]:
list(df_credit)

['Age',
 'Sex',
 'Job',
 'Housing',
 'Saving accounts',
 'Checking account',
 'Credit amount',
 'Duration',
 'Purpose',
 'Risk']

In [10]:
df_credit.describe()

Age          Job  Credit amount     Duration
count  1000.000000  1000.000000    1000.000000  1000.000000
mean     35.546000     1.904000    3271.258000    20.903000
std      11.375469     0.653614    2822.736876    12.058814
min      19.000000     0.000000     250.000000     4.000000
25%      27.000000     2.000000    1365.500000    12.000000
50%      33.000000     2.000000    2319.500000    18.000000
75%      42.000000     2.000000    3972.250000    24.000000
max      75.000000     3.000000   18424.000000    72.000000

In [11]:
df_credit = df_credit.fillna('unknown')

In [12]:
age_ranges      = [list(range(15 + 5*i,15 + 5*i+5)) for i in range(12)]
duration_ranges = [list(range(5*i,5*i+5)) for i in range(14)]

In [13]:
ages = (df_credit['Age'].unique()).tolist()
sexes = (df_credit['Sex'].unique()).tolist()
jobs = (df_credit['Job'].unique()).tolist()
housings = (df_credit['Housing'].unique()).tolist()
save_account = (df_credit['Saving accounts'].unique()).tolist()
check_account = (df_credit['Checking account'].unique()).tolist()
credit_amounts = (df_credit['Credit amount'].unique()).tolist()
durations = (df_credit['Duration'].unique()).tolist()
purposes = (df_credit['Purpose'].unique()).tolist()
risks = (df_credit['Risk'].unique()).tolist()

In [14]:
st = np.std(np.array(credit_amounts)) ; print(st)
mx = np.max(np.array(credit_amounts))
mean =  np.mean(np.array(credit_amounts))  

2888.0675629490124


In [15]:
enc_age = []
enc_sex = []
enc_job = []
enc_house = []
enc_save = []
enc_check = []
enc_credit = []
enc_duration = []
enc_purpo = []
enc_risk = []
for idx in range(len(df_credit)):
    ##--------------
    a = df_credit.iloc[idx]['Age']
    vect = np.zeros((len(age_ranges,)))
    for j in range(len(age_ranges)):
        if a in age_ranges[j]:
            vect[j] = 1
            break
    enc_age.append(vect)
    
    ##-------------
    a = df_credit.iloc[idx]['Sex']
    vect = np.zeros((len(sexes,)))
    ind = sexes.index(a)
    vect[ind] = 1
    enc_sex.append(vect)
    ##------------
    a = df_credit.iloc[idx]['Job']
    vect = np.zeros((len(jobs,)))
    ind = jobs.index(a)
    vect[ind] = 1
    enc_job.append(vect)
    ## -----------
    a = df_credit.iloc[idx]['Housing']
    vect = np.zeros((len(housings,)))
    ind = housings.index(a)
    vect[ind] = 1
    enc_house.append(vect)
    ##____________
    a = df_credit.iloc[idx]['Saving accounts']
    vect = np.zeros((len(save_account,)))
    ind = save_account.index(a)
    vect[ind] = 1
    enc_save.append(vect)
    ##_____________
    a = df_credit.iloc[idx]['Checking account']
    vect = np.zeros((len(check_account,)))
    ind = check_account.index(a)
    vect[ind] = 1
    enc_check.append(vect)
    ##____________
    a = df_credit.iloc[idx]['Credit amount']
    #vect = np.zeros((len(credit_amounts,)))
    #ind = credit_amounts.index(a)
    #vect[ind] = 1
    centred = a/mx #(a - mean)/st
    enc_credit.append(centred)
    ## ___________
    
    a = df_credit.iloc[idx]['Duration']
    vect = np.zeros((len(duration_ranges,)))
    for j in range(len(duration_ranges)):
        if a in duration_ranges[j]:
            vect[j] = 1
            break
    enc_duration.append(vect)
    ##_____________
    a = df_credit.iloc[idx]['Purpose']
    vect = np.zeros((len(purposes,)))
    ind = purposes.index(a)
    vect[ind] = 1
    enc_purpo.append(vect)
    ##____________
    a = df_credit.iloc[idx]['Risk']
    vect = np.zeros((len(risks,)))
    ind = risks.index(a)
    vect[ind] = 1
    enc_risk.append(vect)

In [16]:
enc_age = np.array(enc_age)
enc_sex = np.array(enc_sex)
enc_job = np.array(enc_job)
enc_house = np.array(enc_house)
enc_save = np.array(enc_save)
enc_check = np.array(enc_check)
enc_credit = np.array(enc_credit)
enc_duration = np.array(enc_duration)
enc_purpo = np.array(enc_purpo)
enc_risk = np.array(enc_risk)

In [17]:
risk = np.array([np.argmax(r) for r in enc_risk])

In [18]:
X_all = np.concatenate((enc_age,enc_sex,enc_job,enc_house,enc_save,enc_check,enc_credit.reshape((-1,1)),enc_duration,enc_purpo),axis = 1)

In [33]:
pca = decomposition.PCA()
pca.fit(X_all)
pca_samples = pca.transform(X_all)

In [34]:
fig, ax = plt.subplots(figsize=(14, 5))
sns.set(font_scale=1)
plt.step(range(X_all.shape[1]), pca.explained_variance_ratio_.cumsum(), where='mid',
         label='cumulative explained variance')
sns.barplot(np.arange(1,X_all.shape[1]+1), pca.explained_variance_ratio_, alpha=0.5, color = 'g',
            label='individual explained variance')
plt.xlim(0, 100)

ax.set_xticklabels([s if int(s.get_text())%2 == 0 else '' for s in ax.get_xticklabels()])

plt.ylabel('Explained variance', fontsize = 14)
plt.xlabel('Principal components', fontsize = 14)
plt.legend(loc='upper left', fontsize = 13);

In [20]:
plt.show()

# Explore Data 

# Correlation Study

pca = decomposition.PCA(2)
pca.fit(X_all)
pca_samples = pca.transform(X_all)

In [21]:
from sklearn.decomposition import FastICA 
ICA = FastICA(n_components=30, random_state=0, tol = 0.01) 

In [22]:
X_ICA = ICA.fit_transform(X_all)

In [23]:
hasher = ensemble.RandomTreesEmbedding(n_estimators=200, random_state=0,max_depth=5)
X_transformed = hasher.fit_transform(X_all)
pca = decomposition.TruncatedSVD(30) # Truncated
X_reduced = pca.fit_transform(X_transformed)

In [24]:
X_red_iso = isomap.fit_transform(X_transformed.toarray())

NameError: name 'isomap' is not defined

In [25]:
colors = []
for l in enc_risk:
    if(l[0] == 1):
        colors.append('blue')
    else:
        colors.append('red')

In [23]:
isomap = manifold.Isomap(n_neighbors=6, n_components=30)
X_isomap = isomap.fit_transform(X_all)

In [94]:
ran = np.array(range(1000))
ran_train , ran_test = train_test_split(ran,test_size = 0.3)

In [95]:
X_train_iso , X_test_iso , X_train_ica , X_test_ica, r_train , r_test = X_isomap[ran_train] ,X_isomap[ran_test], \
    X_ICA[ran_train] , X_ICA[ran_test] , enc_risk[ran_train] , enc_risk[ran_test]
X_train_pca , X_test_pca = X_reduced[ran_train] ,X_reduced[ran_test]
risk1 = [np.argmax(x) for x in r_train]
risk2 = [np.argmax(x) for x in r_test]

In [32]:
from keras.models import *
from keras.layers import *

Using TensorFlow backend.


In [162]:
M1 = Sequential()
M1.add(Dense(30,input_shape= (30,)))
M1.add(Activation('relu'))
M1.add(Dense(30))
M1.add(Activation('relu'))
M1.add(Dense(2))
M1.add(Activation('softmax'))

In [168]:
M1.compile(optimizer='adamax',loss='categorical_crossentropy',metrics = ['accuracy']) # categorical_crossentropy

In [170]:
M1.fit(X_train_pca,r_train,epochs = 10, batch_size = 2,validation_data = (X_test_pca,r_test) ) 

Train on 700 samples, validate on 300 samples
Epoch 1/10
700/700 [==============================] - 1s 1ms/step - loss: 0.3101 - acc: 0.8771 - val_loss: 0.6812 - val_acc: 0.6733
Epoch 2/10
700/700 [==============================] - 1s 1ms/step - loss: 0.2967 - acc: 0.8814 - val_loss: 0.6441 - val_acc: 0.7167
Epoch 3/10
700/700 [==============================] - 1s 1ms/step - loss: 0.2907 - acc: 0.8871 - val_loss: 0.6756 - val_acc: 0.6833
Epoch 4/10
700/700 [==============================] - 1s 1ms/step - loss: 0.2799 - acc: 0.8900 - val_loss: 0.6763 - val_acc: 0.6967
Epoch 5/10
700/700 [==============================] - 1s 1ms/step - loss: 0.2737 - acc: 0.8971 - val_loss: 0.6850 - val_acc: 0.7100
Epoch 6/10
700/700 [==============================] - 1s 1ms/step - loss: 0.2635 - acc: 0.9057 - val_loss: 0.7135 - val_acc: 0.6967
Epoch 7/10
700/700 [==============================] - 1s 1ms/step - loss: 0.2579 - acc: 0.9000 - val_loss: 0.7059 - val_acc: 0.7200
Epoch 8/10
700/700 [==========

In [171]:
r_pred_1 = M1.predict(X_test_pca)

### Classifiers 

In [33]:
labels = [np.argmax(l) for l in r_pred]
orig = [np.argmax(l) for l in r_test]

NameError: name 'r_pred_1' is not defined

In [173]:
print("Accuracy Score",accuracy_score(risk2,labels))
print("Classification Report",classification_report(risk2,labels))
print("Conf. Matrix \n",confusion_matrix(risk2,labels))

Accuracy Score 0.7066666666666667
Classification Report              precision    recall  f1-score   support

          0       0.78      0.83      0.80       214
          1       0.49      0.41      0.44        86

avg / total       0.69      0.71      0.70       300

Conf. Matrix 
 [[177  37]
 [ 51  35]]


In [34]:
from sklearn.ensemble import RandomForestClassifier

In [70]:
rf = RandomForestClassifier(max_depth=None, max_features=X_train_pca.shape[1], n_estimators=15, random_state=2)
rf.fit(X_train_pca,risk1)
r_rf = rf.predict(X_test_pca)
print("Accuracy Score",accuracy_score(risk2,r_rf))
print("Classification Report",classification_report(risk2,r_rf))
print("Conf. Matrix \n",confusion_matrix(risk2,r_rf))

Accuracy Score 0.6766666666666666
Classification Report              precision    recall  f1-score   support

          0       0.77      0.78      0.77       213
          1       0.44      0.41      0.43        87

avg / total       0.67      0.68      0.67       300

Conf. Matrix 
 [[167  46]
 [ 51  36]]


In [73]:
tree = DecisionTreeClassifier()
tree.fit(X_train_iso,risk1)
r_tree = tree.predict(X_test_iso)

In [74]:
print("Accuracy Score",accuracy_score(risk2,r_tree))
print("Classification Report",classification_report(risk2,r_tree))
print("Conf. Matrix \n",confusion_matrix(risk2,r_tree))

Accuracy Score 0.6266666666666667
Classification Report              precision    recall  f1-score   support

          0       0.75      0.72      0.73       213
          1       0.37      0.40      0.38        87

avg / total       0.64      0.63      0.63       300

Conf. Matrix 
 [[153  60]
 [ 52  35]]


In [75]:
# Gaussian 
from sklearn.naive_bayes import GaussianNB

In [78]:
NB = GaussianNB()
NB.fit(X_train_iso,risk1)
r_nb = NB.predict(X_test_iso)

In [79]:
print("Accuracy Score",accuracy_score(risk2,r_nb))
print("Classification Report",classification_report(risk2,r_nb))
print("Conf. Matrix \n",confusion_matrix(risk2,r_nb))

Accuracy Score 0.7066666666666667
Classification Report              precision    recall  f1-score   support

          0       0.78      0.82      0.80       213
          1       0.49      0.44      0.46        87

avg / total       0.70      0.71      0.70       300

Conf. Matrix 
 [[174  39]
 [ 49  38]]


In [93]:
clf = discriminant_analysis.LinearDiscriminantAnalysis()
clf.fit(X_train_ica, risk1) # Quadratic
r_lda = clf.predict(X_test_ica)
print("Accuracy Score",accuracy_score(risk2,r_lda))
print("Classification Report",classification_report(risk2,r_lda))
print("Conf. Matrix \n",confusion_matrix(risk2,r_lda))

Accuracy Score 0.69
Classification Report              precision    recall  f1-score   support

          0       0.77      0.80      0.79       213
          1       0.46      0.43      0.44        87

avg / total       0.68      0.69      0.69       300

Conf. Matrix 
 [[170  43]
 [ 50  37]]


In [52]:
clfq = discriminant_analysis.QuadraticDiscriminantAnalysis().fit(X_train_ica, risk1) 
r_qda = clfq.predict(X_test_ica)

In [53]:
print("Accuracy Score",accuracy_score(risk2,r_qda))
print("Classification Report",classification_report(risk2,r_qda))
print("Conf. Matrix \n",confusion_matrix(risk2,r_qda))

Accuracy Score 0.6333333333333333
Classification Report              precision    recall  f1-score   support

          0       0.79      0.65      0.72       213
          1       0.41      0.59      0.48        87

avg / total       0.68      0.63      0.65       300

Conf. Matrix 
 [[139  74]
 [ 36  51]]


In [55]:
xgb = XGBClassifier()
xgb.fit(X_train_iso,risk1)
r_xgb = xgb.predict(X_test_iso)
print("Accuracy Score",accuracy_score(risk2,r_xgb),"\n ----------------")
print("Classification Report \n",classification_report(risk2,r_xgb),"\n ----------------")
print("Conf. Matrix \n",confusion_matrix(risk2,r_xgb),"\n ----------------")

Accuracy Score 0.6933333333333334 
 ----------------
Classification Report 
              precision    recall  f1-score   support

          0       0.75      0.85      0.80       213
          1       0.46      0.30      0.36        87

avg / total       0.66      0.69      0.67       300
 
 ----------------
Conf. Matrix 
 [[182  31]
 [ 61  26]] 
 ----------------


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [65]:
svm = SVC(gamma='auto')
svm.fit(X_train_iso,risk1)
r_svm = svm.predict(X_test_iso)
print("Accuracy Score",accuracy_score(risk2,r_svm),"\n ----------------")
print("Classification Report",classification_report(risk2,r_svm),"\n ----------------")
print("Conf. Matrix \n",confusion_matrix(risk2,r_svm),"\n ----------------")

Accuracy Score 0.7433333333333333 
 ----------------
Classification Report              precision    recall  f1-score   support

          0       0.77      0.92      0.84       213
          1       0.61      0.31      0.41        87

avg / total       0.72      0.74      0.71       300
 
 ----------------
Conf. Matrix 
 [[196  17]
 [ 60  27]] 
 ----------------


In [58]:
svm = SVC(gamma='auto')
svm.fit(X_train_pca,risk1)
r_svm = svm.predict(X_test_pca)
print("Accuracy Score",accuracy_score(risk2,r_svm),"\n ----------------")
print("Classification Report",classification_report(risk2,r_svm),"\n ----------------")
print("Conf. Matrix \n",confusion_matrix(risk2,r_svm),"\n ----------------")

Accuracy Score 0.7033333333333334 
 ----------------
Classification Report              precision    recall  f1-score   support

          0       0.75      0.88      0.81       213
          1       0.48      0.28      0.35        87

avg / total       0.67      0.70      0.68       300
 
 ----------------
Conf. Matrix 
 [[187  26]
 [ 63  24]] 
 ----------------


#### Reduce size with embedding layers

In [83]:
M1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 100)               3100      
_________________________________________________________________
activation_1 (Activation)    (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 100)               10100     
_________________________________________________________________
activation_2 (Activation)    (None, 100)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 202       
Total params: 13,402
Trainable params: 13,402
Non-trainable params: 0
_________________________________________________________________


In [84]:
M1.pop()

In [85]:
X_hidden_mlp_test = M1.predict(X_test_pca)

In [86]:
X_hidden_mlp_train = M1.predict(X_train_pca)

In [68]:
X_hidden_train_tsne = tsne.fit_transform(X_hidden_mlp_train)

[t-SNE] Computing 151 nearest neighbors...
[t-SNE] Indexed 700 samples in 0.060s...
[t-SNE] Computed neighbors for 700 samples in 0.027s...
[t-SNE] Computed conditional probabilities for sample 700 / 700
[t-SNE] Mean sigma: 0.011263
[t-SNE] Computed conditional probabilities in 0.130s
[t-SNE] Iteration 50: error = 47.0303612, gradient norm = 0.3292722 (50 iterations in 1.573s)
[t-SNE] Iteration 100: error = 44.5664902, gradient norm = 0.3418933 (50 iterations in 1.594s)
[t-SNE] Iteration 150: error = 43.9504318, gradient norm = 0.3220161 (50 iterations in 1.514s)
[t-SNE] Iteration 200: error = 44.0260506, gradient norm = 0.3254810 (50 iterations in 1.539s)
[t-SNE] Iteration 250: error = 43.7992172, gradient norm = 0.3216765 (50 iterations in 1.653s)
[t-SNE] KL divergence after 250 iterations with early exaggeration: 43.799217
[t-SNE] Iteration 300: error = 0.2168154, gradient norm = 0.0015733 (50 iterations in 1.514s)
[t-SNE] Iteration 350: error = 0.1555422, gradient norm = 0.0002697 

In [91]:
X_hidden_test_tsne = tsne.fit_transform(X_hidden_mlp_test)

[t-SNE] Computing 151 nearest neighbors...
[t-SNE] Indexed 300 samples in 0.000s...
[t-SNE] Computed neighbors for 300 samples in 0.164s...
[t-SNE] Computed conditional probabilities for sample 300 / 300
[t-SNE] Mean sigma: 2.144005
[t-SNE] Computed conditional probabilities in 0.029s
[t-SNE] Iteration 50: error = 59.4988060, gradient norm = 0.5027621 (50 iterations in 0.701s)
[t-SNE] Iteration 100: error = 59.8181648, gradient norm = 0.5166724 (50 iterations in 0.712s)
[t-SNE] Iteration 150: error = 61.3853340, gradient norm = 0.5075765 (50 iterations in 0.739s)
[t-SNE] Iteration 200: error = 62.3165588, gradient norm = 0.5187105 (50 iterations in 0.734s)
[t-SNE] Iteration 250: error = 62.0209045, gradient norm = 0.4940045 (50 iterations in 0.722s)
[t-SNE] KL divergence after 250 iterations with early exaggeration: 62.020905
[t-SNE] Iteration 300: error = 1.0827872, gradient norm = 0.0039137 (50 iterations in 0.660s)
[t-SNE] Iteration 350: error = 1.0205365, gradient norm = 0.0019032 

convex_hulls_tsne = exo4.convexHulls(X_hidden_tsne_test[:,:2], risk2)
ellipses_tsne = exo4.best_ellipses(X_hidden_tsne_test[:,:2], risk2)
nh_tsne = exo4.neighboring_hit(X_hidden_tsne_test[:,:2], risk2)

visualization(X_hidden_tsne_test[:,:2], risk2, convex_hulls = convex_hulls_tsne, ellipses = ellipses_tsne,projname = 't-SNE', nh = nh_tsne)

In [92]:
neigh = KNeighborsClassifier(n_neighbors=6)
#neigh.fit(X, y) 

In [101]:
X_transformed = hasher.fit_transform(X_hidden_mlp_test)
pca = decomposition.TruncatedSVD(30) # Truncated
X_red_test = pca.fit_transform(X_transformed)

In [99]:
neigh.fit(X_red, risk1) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [102]:
r_knn = neigh.predict(X_red_test)

In [103]:
print("Accuracy Score",accuracy_score(risk2,r_knn),"\n ----------------")
print("Classification Report \n",classification_report(risk2,r_knn),"\n ----------------")
print("Conf. Matrix \n",confusion_matrix(risk2,r_knn),"\n ----------------")

Accuracy Score 0.6366666666666667 
 ----------------
Classification Report 
              precision    recall  f1-score   support

          0       0.70      0.85      0.76       208
          1       0.32      0.16      0.22        92

avg / total       0.58      0.64      0.60       300
 
 ----------------
Conf. Matrix 
 [[176  32]
 [ 77  15]] 
 ----------------
